---
title: "UsageExample"
output:
  pdf_document: default
  html_document: default
---

#Project Usage Example

## Download Repo

```{r}
rm(list = ls())
#cred <- git2r::cred_user_pass(rstudioapi::askForPassword("username"), rstudioapi::askForPassword("Password"))
#devtools::install_git("https://git-inf.technikum-wien.at/finance/finance2021/pkgs/pittl_hafner_luo.git",credentials = cred)

#alternative: 
devtools::install_git("https://github.com/anewruser/finance.git")

```

```{r}
#devtools::install_git("https://git-inf.technikum-wien.at/finance/finance2021/pkgs/catsar.git", credentials = cred)
```


```{r}
library(pittlHafnerLuo)
```


## Help
```{r}
?pittlHafnerLuo::get_index
```


# Usage Examples

## FCS

Unfortunatly, the ATX is not supported by that API!

```{r}
pittlHafnerLuo::get_index("Dow Jones","fcs","united-states")
```


```{r}
Sys.sleep(60)
pittlHafnerLuo::get_index("DAX","fcs","germany")
```


```{r}
Sys.sleep(60)
pittlHafnerLuo::get_index("JASDAQ","fcs","japan")
```




## Yahoo Finance

```{r}
pittlHafnerLuo::get_index("ATX")
```


```{r}
pittlHafnerLuo::get_index("GDAXI") #identifiers are at least partly available

```

For US shares, we also ahve identifiers and sedol!

```{r}
pittlHafnerLuo::get_index("IXIC")

```

```{r}

pittlHafnerLuo::get_index("OMX")

```


Also for that mambers, we get identifiers!

```{r}

pittlHafnerLuo::get_index("IXIC") #nasdaq
```

